export type Language = "en" | "es" | "fr" | "de" | "ja" | "zh"

export const translations: Record<Language, Record<string, string>> = {
  en: {
    play: "Play",
    settings: "Settings",
    shop: "Shop",
    level: "Level",
    moves: "Moves",
    time: "Time",
    hint: "Hint",
    undo: "Undo",
    restart: "Restart",
    pause: "Pause",
    resume: "Resume",
    quit: "Quit",
    congratulations: "Congratulations!",
    levelComplete: "Level Complete",
    nextLevel: "Next Level",
    mainMenu: "Main Menu",
    sound: "Sound",
    music: "Music",
    colorBlindMode: "Color Blind Mode",
    language: "Language",
    coins: "Coins",
    buyHints: "Buy Hints",
    buyUndos: "Buy Undos",
    watchAd: "Watch Ad",
    noHints: "No hints remaining!",
    noUndos: "No undos remaining!",
    back: "Back",
    select: "Select a level",
    beginner: "Beginner",
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    expert: "Expert",
  },
  es: {
    play: "Jugar",
    settings: "Ajustes",
    shop: "Tienda",
    level: "Nivel",
    moves: "Movimientos",
    time: "Tiempo",
    hint: "Pista",
    undo: "Deshacer",
    restart: "Reiniciar",
    pause: "Pausar",
    resume: "Continuar",
    quit: "Salir",
    congratulations: "¡Felicidades!",
    levelComplete: "Nivel Completado",
    nextLevel: "Siguiente Nivel",
    mainMenu: "Menú Principal",
    sound: "Sonido",
    music: "Música",
    colorBlindMode: "Modo Daltónico",
    language: "Idioma",
    coins: "Monedas",
    buyHints: "Comprar Pistas",
    buyUndos: "Comprar Deshacer",
    watchAd: "Ver Anuncio",
    noHints: "¡Sin pistas!",
    noUndos: "¡Sin deshacer!",
    back: "Atrás",
    select: "Selecciona un nivel",
    beginner: "Principiante",
    easy: "Fácil",
    medium: "Medio",
    hard: "Difícil",
    expert: "Experto",
  },
  fr: {
    play: "Jouer",
    settings: "Paramètres",
    shop: "Boutique",
    level: "Niveau",
    moves: "Coups",
    time: "Temps",
    hint: "Indice",
    undo: "Annuler",
    restart: "Recommencer",
    pause: "Pause",
    resume: "Reprendre",
    quit: "Quitter",
    congratulations: "Félicitations!",
    levelComplete: "Niveau Terminé",
    nextLevel: "Niveau Suivant",
    mainMenu: "Menu Principal",
    sound: "Son",
    music: "Musique",
    colorBlindMode: "Mode Daltonien",
    language: "Langue",
    coins: "Pièces",
    buyHints: "Acheter Indices",
    buyUndos: "Acheter Annuler",
    watchAd: "Voir Pub",
    noHints: "Plus d'indices!",
    noUndos: "Plus d'annuler!",
    back: "Retour",
    select: "Sélectionnez un niveau",
    beginner: "Débutant",
    easy: "Facile",
    medium: "Moyen",
    hard: "Difficile",
    expert: "Expert",
  },
  de: {
    play: "Spielen",
    settings: "Einstellungen",
    shop: "Shop",
    level: "Level",
    moves: "Züge",
    time: "Zeit",
    hint: "Hinweis",
    undo: "Rückgängig",
    restart: "Neustart",
    pause: "Pause",
    resume: "Fortsetzen",
    quit: "Beenden",
    congratulations: "Glückwunsch!",
    levelComplete: "Level Geschafft",
    nextLevel: "Nächstes Level",
    mainMenu: "Hauptmenü",
    sound: "Ton",
    music: "Musik",
    colorBlindMode: "Farbenblind-Modus",
    language: "Sprache",
    coins: "Münzen",
    buyHints: "Hinweise Kaufen",
    buyUndos: "Rückgängig Kaufen",
    watchAd: "Werbung Ansehen",
    noHints: "Keine Hinweise mehr!",
    noUndos: "Kein Rückgängig mehr!",
    back: "Zurück",
    select: "Wähle ein Level",
    beginner: "Anfänger",
    easy: "Leicht",
    medium: "Mittel",
    hard: "Schwer",
    expert: "Experte",
  },
  ja: {
    play: "プレイ",
    settings: "設定",
    shop: "ショップ",
    level: "レベル",
    moves: "手数",
    time: "時間",
    hint: "ヒント",
    undo: "戻す",
    restart: "リスタート",
    pause: "一時停止",
    resume: "再開",
    quit: "終了",
    congratulations: "おめでとう！",
    levelComplete: "レベルクリア",
    nextLevel: "次のレベル",
    mainMenu: "メインメニュー",
    sound: "サウンド",
    music: "音楽",
    colorBlindMode: "色覚モード",
    language: "言語",
    coins: "コイン",
    buyHints: "ヒントを購入",
    buyUndos: "戻すを購入",
    watchAd: "広告を見る",
    noHints: "ヒントがありません！",
    noUndos: "戻すがありません！",
    back: "戻る",
    select: "レベルを選択",
    beginner: "初心者",
    easy: "簡単",
    medium: "普通",
    hard: "難しい",
    expert: "エキスパート",
  },
  zh: {
    play: "开始游戏",
    settings: "设置",
    shop: "商店",
    level: "关卡",
    moves: "步数",
    time: "时间",
    hint: "提示",
    undo: "撤销",
    restart: "重新开始",
    pause: "暂停",
    resume: "继续",
    quit: "退出",
    congratulations: "恭喜！",
    levelComplete: "关卡完成",
    nextLevel: "下一关",
    mainMenu: "主菜单",
    sound: "音效",
    music: "音乐",
    colorBlindMode: "色盲模式",
    language: "语言",
    coins: "金币",
    buyHints: "购买提示",
    buyUndos: "购买撤销",
    watchAd: "观看广告",
    noHints: "没有提示了！",
    noUndos: "没有撤销了！",
    back: "返回",
    select: "选择关卡",
    beginner: "新手",
    easy: "简单",
    medium: "中等",
    hard: "困难",
    expert: "专家",
  },
}

export function t(key: string, language: Language = "en"): string {
  return translations[language]?.[key] || translations.en[key] || key
}

export const languageNames: Record<Language, string> = {
  en: "English",
  es: "Español",
  fr: "Français",
  de: "Deutsch",
  ja: "日本語",
  zh: "中文",
}
